version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab1
    restart: always
    hostname: gitlab.local.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./path/to/gitlab/config:/etc/gitlab
      - ./path/to/gitlab/logs:/var/log/gitlab
      - ./path/to/gitlab/data:/var/opt/gitlab
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'https://gitlab.local.com'; nginx['redirect_http_to_https'] = true;"
